const ADD_RECIPE = 'RECIPES';
const SET_RECIPES = 'SET_RECIPES';
const DELETE_RECIPE = 'DELETE_RECIPE';
const SELECT_RECIPE_ID = 'SELECT_RECIPE_ID';
const UPDATE_RECIPE_BY_ID = 'UPDATE_RECIPE_BY_ID';
const SET_THEME_MODE = 'SET_THEME_MODE';
const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
const SET_AUTH = 'SET_AUTH';
const SET_USER = 'SET_USER';
const LOGIN_USER = 'LOGIN_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const REGISTER_USER = 'REGISTER_USER';
const SET_INITIAL_RECIPE = 'SELECT_INITIAL_RECIPE';
const SET_IS_VALID = 'SET_IS_VALID';
const SET_LANG = 'SET_LANG';

const types = {
    SET_AUTH,
    ADD_RECIPE,
    DELETE_RECIPE,
    SELECT_RECIPE_ID,
    UPDATE_RECIPE_BY_ID,
    SET_SEARCH_QUERY,
    SET_THEME_MODE,
    SET_USER,
    LOGIN_USER,
    LOGOUT_USER,
    REGISTER_USER,
    SET_RECIPES,
    SET_INITIAL_RECIPE,
    SET_IS_VALID,
    SET_LANG,
}
export default types;